DROP SCHEMA IF EXISTS MiniWineBar;
CREATE SCHEMA MiniWineBar;
USE MiniWineBar;

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	PRECOUNITARIO FLOAT (6,2) UNSIGNED NOT NULL,
	UNMEDIDA VARCHAR(50) NOT NULL,
	VALORMEDIDA FLOAT (6,2) UNSIGNED NOT NULL,
    TIPO VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPRA(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	VALORFINAL FLOAT (6,2) NOT NULL,
	STATUSCOMPRA VARCHAR(50) NOT NULL,
	METODOPAGAMENTO VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS ITEMCOMPRA(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	QUANTIDADE INT UNSIGNED NOT NULL,
	VALORTOTAL FLOAT (6,2) NOT NULL,
	IDPRODUTO INT UNSIGNED NOT NULL,
	IDCOMPRA INT UNSIGNED
);

ALTER TABLE ITEMCOMPRA ADD FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (ID);
ALTER TABLE ITEMCOMPRA ADD FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA (ID);

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECOUNITARIO, VALORMEDIDA, UNMEDIDA, TIPO) VALUES 
	('Vinho Tinto Suave São José','Vinho de mesa tinto tipo suave da marca São José', '8.75', '600', 'unidade', 'Vinho'),
	('Rolha especial','Rolha a vulsa especial para lacre de garrafas em geral', '5', '1', 'ml', 'Acessórios');
                     
INSERT INTO COMPRA (VALORFINAL, STATUSCOMPRA, METODOPAGAMENTO) VALUES 
	('32.5', 'Aguardadno pagamento', 'Indisponível'),
	('28.75', 'Concluído', 'Indisponível');

INSERT INTO ITEMCOMPRA (QUANTIDADE, VALORTOTAL, IDPRODUTO, IDCOMPRA) VALUES 
	('2','17.5', '1', '1'),
	('3','15', '2', '1'),
	('1','8.75', '1', '2'),
	('4','20', '2', '2');

